"""
Django settings for KDPSproject project.

Generated by 'django-admin startproject' using Django 4.0.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-403mua#8lr^m1a*t%+n=so&!*r3%zxqlg-s@z#f)^u#8lpw9%2'


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'KDPS',  # KDPSアプリを追加
    'accounts', 
    'Exam',
    'studentmenu',
    'Grades',  # Gradesアプリを追加
    'Grademenu',
    'two_step_verification',
    'login',
    'student_register',
    'teacher_register',
    'permissions',
    'StudentList',
    'DBzikken',
    'test_list',
    'Log_Action',
    'Log_Error',
    'grading',
    'TeacherList',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'KDPSproject.urls'


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / 'KDPS/templates',        # KDPSの全体テンプレートディレクトリ
            BASE_DIR / 'KDPS/templates/KDPS',  # KDPS配下のテンプレートディレクトリ
            BASE_DIR / 'DBzikken/templates',   # DBzikkenのテンプレートディレクトリ
            BASE_DIR / 'login/templates',  # loginアプリのテンプレートディレクトリを追加
        ],
        'APP_DIRS': True,  # 各アプリケーションのテンプレートディレクトリを自動で検出
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.template.context_processors.i18n',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'KDPSproject.wsgi.application'


# Database
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]
AUTH_USER_MODEL = 'auth.User'


# Internationalization
LANGUAGE_CODE = 'ja'  # 日本語設定

TIME_ZONE = 'Asia/Tokyo'  # 日本時間に設定

USE_I18N = True

USE_L10N = True  # ローカライズを有効に

USE_TZ = True


# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'

# 静的ファイルのディレクトリを指定
STATICFILES_DIRS = [
    BASE_DIR / 'KDPSproject' / 'static',  # KDPSproject の static ディレクトリを指定
]

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# メール送信設定
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'  # SMTP バックエンド
EMAIL_HOST = 'smtp.gmail.com'  # SMTPサーバーアドレス
EMAIL_PORT = 587  # SMTPポート
EMAIL_USE_TLS = True  # TLSの使用を有効化
EMAIL_HOST_USER = 'oky.KDPS@gmail.com'  # 送信元のメールアドレス
EMAIL_HOST_PASSWORD = 'zsny bzbo ghqf mvww'  # Gmailアカウントのアプリパスワード
DEFAULT_FROM_EMAIL = 'noreply@example.com'  # デフォルト送信者メールアドレス

LOGOUT_REDIRECT_URL = '/login'

load_dotenv(os.path.join(BASE_DIR, '.env'))

# 環境変数からAPIキーを取得
GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")

# その他の設定
SIMILARITY_THRESHOLD_HIGH = 0.9
SIMILARITY_THRESHOLD_MEDIUM = 0.7

# ログ設定
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'file': {
            'level': 'ERROR',
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'errors.log'),
        },
    },
    'loggers': {
        '': {
            'handlers': ['file'],
            'level': 'ERROR',
            'propagate': True,
        },
    },
}
