# Generated by Django 5.1.2 on 2024-11-28 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KDPS', '0002_user_role_alter_actionlog_log_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='email',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
