# Generated by Django 5.1.2 on 2024-11-28 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KDPS', '0003_teacher_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='email',
            field=models.CharField(default='', max_length=30),
        ),
    ]
