# Generated by Django 5.1.2 on 2024-11-29 02:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KDPS', '0004_alter_teacher_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradingCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='test',
            name='name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test',
            name='total_score',
            field=models.IntegerField(default=100),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('question_type', models.CharField(choices=[('objective', '選択問題'), ('descriptive', '記述問題')], default='descriptive', max_length=20)),
                ('correct_answer', models.TextField()),
                ('choices', models.TextField(blank=True, null=True)),
                ('score', models.IntegerField(default=10)),
                ('partial_scoring_conditions', models.TextField(blank=True, help_text="部分点条件（記述問題用）。例: '重要なキーワード1:3, 重要なキーワード2:5'", null=True)),
                ('test', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='KDPS.test')),
            ],
        ),
        migrations.CreateModel(
            name='ConversationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_answer', models.TextField()),
                ('feedback', models.TextField()),
                ('score', models.IntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='history', to='KDPS.question')),
            ],
        ),
        migrations.CreateModel(
            name='TempAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('answer_text', models.TextField()),
                ('is_finalized', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KDPS.question')),
            ],
        ),
    ]
