# Generated by Django 4.0 on 2024-11-12 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0002_conversationhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationhistory',
            name='prompt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conversationhistory',
            name='wikipedia_info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
