# Generated by Django 5.1.2 on 2024-11-27 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0003_conversationhistory_prompt_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradingCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='conversationhistory',
            name='prompt',
        ),
        migrations.RemoveField(
            model_name='conversationhistory',
            name='wikipedia_info',
        ),
        migrations.AddField(
            model_name='conversationhistory',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='choices',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('objective', '選択問題'), ('descriptive', '記述問題')], default='descriptive', max_length=20),
        ),
    ]
