# Generated by Django 5.1.2 on 2024-11-27 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0004_gradingcriteria_remove_conversationhistory_prompt_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='conversationhistory',
            name='correct_answer',
        ),
        migrations.RemoveField(
            model_name='conversationhistory',
            name='question_text',
        ),
        migrations.AddField(
            model_name='conversationhistory',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='history', to='grading.question'),
        ),
        migrations.AddField(
            model_name='question',
            name='test',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='grading.test'),
        ),
    ]
