# Generated by Django 5.1.2 on 2024-11-27 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0005_test_remove_conversationhistory_correct_answer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('answer_text', models.TextField()),
                ('is_finalized', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grading.question')),
            ],
        ),
    ]
