# Generated by Django 5.1.2 on 2024-11-27 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0006_tempanswer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempanswer',
            name='user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
