# Generated by Django 5.1.2 on 2024-11-27 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0007_alter_tempanswer_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='score',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='test',
            name='total_score',
            field=models.IntegerField(default=100),
        ),
    ]
