# Generated by Django 5.1.2 on 2024-11-28 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0008_question_score_test_total_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='partial_scoring_conditions',
            field=models.TextField(blank=True, help_text="部分点条件（記述問題用）。例: '重要なキーワード1:3, 重要なキーワード2:5'", null=True),
        ),
    ]
