# Generated by Django 5.1.2 on 2024-11-14 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActionLog',
            fields=[
                ('log_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('action', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='AuthTokens',
            fields=[
                ('token_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('token', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('error_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('error_message', models.TextField(max_length=200)),
                ('timestamp', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.IntegerField(primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=20)),
                ('school_year', models.IntegerField()),
                ('student_class', models.CharField(max_length=3)),
                ('email', models.CharField(max_length=30)),
                ('parent_email', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('teacher_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('teacher_name', models.CharField(max_length=20)),
                ('school_year', models.IntegerField()),
                ('student_class', models.CharField(max_length=3)),
                ('post', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('test_id', models.IntegerField(primary_key=True, serialize=False)),
                ('test_name', models.CharField(max_length=20)),
                ('teacher_id', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Grades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_id', models.IntegerField()),
                ('score', models.IntegerField()),
                ('answer_image', models.BinaryField()),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KDPS.student')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('teacher_id', models.CharField(blank=True, max_length=10, null=True)),
                ('password', models.CharField(max_length=12)),
                ('authority', models.IntegerField()),
                ('student_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='KDPS.student')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=20, verbose_name='学籍番号')),
                ('grade', models.PositiveIntegerField(verbose_name='学年')),
                ('class_name', models.CharField(max_length=50, verbose_name='クラス')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='KDPS.user')),
            ],
        ),
    ]
