# Generated by Django 5.1.1 on 2024-11-25 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KDPS', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', '学生'), ('teacher', '教師'), ('admin', '管理者')], default='student', max_length=10),
        ),
        migrations.AlterField(
            model_name='actionlog',
            name='log_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='actionlog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
