# Generated by Django 5.1.2 on 2024-11-19 01:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KDPS', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.AlterField(
            model_name='grades',
            name='test_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KDPS.test'),
        ),
        migrations.AlterField(
            model_name='test',
            name='test_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
