# Generated by Django 5.1.1 on 2024-11-19 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KDPS', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
    ]
