# Generated by Django 5.1.2 on 2024-11-29 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KDPS', '0005_gradingcriteria_test_name_test_total_score_question_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeminiTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('total_score', models.IntegerField(default=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='test',
            name='name',
        ),
        migrations.RemoveField(
            model_name='test',
            name='total_score',
        ),
    ]
