# Generated by Django 5.1.5 on 2025-01-22 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KDPS', '0007_profile_role_profile_user_alter_profile_class_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(default='1234', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='password',
            field=models.CharField(default=1234, max_length=128),
            preserve_default=False,
        ),
    ]
